// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    DarkBottom: typeof import('./src/components/DarkBottom.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    NDivider: typeof import('naive-ui')['NDivider']
    NMenu: typeof import('naive-ui')['NMenu']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export { }
