// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    DarkBottom: typeof import('./src/components/DarkBottom.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserCard: typeof import('./src/components/UserCard/index.vue')['default']
  }
}

export { }
